name: tergov
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  awesome_extensions: ^2.0.18
  iconsax: ^0.0.8
  gap: ^3.0.1
  flutter_bloc: ^8.1.6
  go_router: ^14.2.8
  cupertino_icons: ^1.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
